{"name": "Проверка появления номера нового заказа на экране 'Лента заказов' в разделе 'В работе'", "status": "broken", "statusDetails": {"message": "TypeError: 'NoneType' object is not callable", "trace": "self = <tests.test_order_page.TestOrderPage object at 0x0000010426698C50>, authorize_user = <pages.main_page.MainPage object at 0x000001042674FA10>\ncreate_order = None\n\n>   ???\nE   TypeError: 'NoneType' object is not callable\n\ntests\\test_order_page.py:101: TypeError"}, "description": "Создаём заказ и проверяем что его номер отображается на экране 'Лента заказов' в разделе 'В работе'", "parameters": [{"name": "driver", "value": "'chrome'"}], "start": 1737466635114, "stop": 1737466635114, "uuid": "f3faba1a-8238-4d19-92b3-f777b4eefcb3", "historyId": "f8ecfb6d1bbc8ea62df29c3b8327bc76", "testCaseId": "482e79e860da43b280270f71ad5c519a", "fullName": "tests.test_order_page.TestOrderPage#test_number_appears_in_progress_section_success", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_order_page"}, {"name": "subSuite", "value": "TestOrderPage"}, {"name": "host", "value": "01ms32"}, {"name": "thread", "value": "25948-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_order_page"}]}